services:
  backend:
    build:
      context: ./backend
    container_name: pitch_correction_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/uploads
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    container_name: pitch_correction_frontend
    ports:
     - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true
